### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eeelolmeisbol** [AlexFlipnote/discord_bot.py#32]
Can somebody help, when i typed `python3 index.py`it showed me this error:
```
[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]
```

**Comment by Soheab** [comment]
try this

If you're getting the [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108) error on a Windows host do the following:

Download and install this certificate here: https://crt.sh/?id=2835394
--> It can be installed by double clicking the file and installing it to Local Computer, download link location: https://beans-took-my-kids.reeee.ee/38qB2n.png

For those curious, it was caused by this:
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

`from ?tag sslfix in the discord.py server`

**Comment by AlexFlipnote** [comment]
Works fine for me

![](https://i.alexflipnote.dev/2Eq2eFP.png)

**Comment by eeelolmeisbol** [comment]
But i am using mac

Am Sa., 11. Juli 2020 um 22:53 Uhr schrieb AlexFlipnote <
notifications@github.com>:

**Comment by Soheab** [comment]
> But i am using mac 

ah then try this

Getting [SSL: CERTIFICATE_VERIFY_FAILED] on Python 3 on OS X?
Navigate to your Applications/Python 3.X/ folder and double click the Install Certificates.command to fix this.
Happy coding!

`from ?tag ssl in the discord.py server`
